# Generated by Django 4.1.7 on 2023-07-07 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_remove_animals_id_alter_animals_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('place', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('images', models.ImageField(upload_to='')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Animals',
        ),
    ]
